### ISSUE TITLE
关于 Arnold 变换的实现

### ISSUE THREAD

**Issue by bbbbx** [GooZy/EasyW#2]
Hi，我在网上搜索 Arnold 变换，搜到了这里，但关于 Arnold 变换的实现代码似乎有点问题？

[https://github.com/GooZy/EasyW/blob/master/easyw/common/utils.py#L35](https://github.com/GooZy/EasyW/blob/master/easyw/common/utils.py#L35)

```diff
for i in range(N):
        for x in range(h):
            for y in range(w):
-                nx = ((a * x + b * y) % w + w) % w  
-                ny = ((c * x + d * y) % w + w) % w
+               nx = ((a * x + b * y) % w)
+               ny = ((c * x + d * y) % w)
                nx = int(nx)
                ny = int(ny)
                new_img[nx, ny] = img[x, y]
        img = copy.deepcopy(new_img)
```

对 `w` 取模后又加上 `w`，然后又对 `w` 取模，好像结果是一样的。即

`x % w == ((x % w) + w) % w`

Arnold 变换公式也没有后面的两部
操作，所以就开了个 issue😂。

**Comment by bbbbx** [comment]
OK，了解了，取模和取余是不同的。

不过，Python 中的 `%` 操作似乎是取模，而 C 中的 `%` 操作是取余。

**Comment by GooZy** [comment]
@bbbbx 嗯，确实是。之前也没注意到python默认是取模
